name: sequencia
description: "A Flutter Game to test your friends synchronization"
publish_to: 'none'

version: 1.3.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  injectable: ^2.3.2
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  provider: ^6.1.2
  reorderables: ^0.6.0
  lottie: ^3.1.2
  just_audio: ^0.9.40
  animated_reorderable_list: ^1.1.1
  wakelock_plus: ^1.2.8
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  package_info_plus: ^9.0.0
  google_mobile_ads: ^6.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-sequencia.jpg"
  min_sdk_android: 23

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Light.ttf
          weight: 300
        - asset: assets/fonts/Fredoka-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fredoka-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fredoka-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fredoka-Bold.ttf
          weight: 700
